### ISSUE TITLE
AnnexBReader在读取最后一个Nalu表现不正确

### ISSUE THREAD

**Issue by rainluoyu** [redknotmiaoyuqiao/EyerH264Decoder#1]
我在跟着大佬学习h264解码器的过程中尝试使用rust实现相应的功能，在实现Lesson_2_3_ReadAnnexB时C++代码与Rust代码在最后一个Nalu表现不一致，我手动打开了h264原始数据，发现最后一个Nalu的bufLen应该是39，但C++的输出是160。

![原始数据](https://user-images.githubusercontent.com/32390158/212632642-638a224e-0934-444a-b82a-887c0f29a851.png)

![C++的输出](https://user-images.githubusercontent.com/32390158/212632890-b4db429e-af04-4c84-b8db-16f31e108714.png)

我认为这可能是一个bug，但也暂时没发现问题出在哪，又或者是我听课时漏了什么。我尝试让C++打印出Nalu中的原始信息，发现C++输出完39字节原始信息后还继续输出了其他不应该存在的字节。希望大佬可以看看是我的问题还是代码存在一些隐秘的bug。

**Comment by redknotmiaoyuqiao** [comment]
非常感谢你的反馈，因为在过春节，这么晚才回复你。

这是我代码里面的 Bug，现在已经修复了。

问题在于 AnnexBReader::ReadFromFile() 函数中，每次从文件中读取完毕，向 Buffer 中追加数据的时候，每次都追加了固定的 1024 个字节，实际上应该按照实际读取的长度进行追加。

目前这份代码做了一些修改，又之前的每一课一个子目录，变成只有一个目录，而通过 tag 来区分是那节课的内容。

你可以通过 H264_AnnexBReader 标签来获取到这一小节的代码。并且之后的 tag 中的这部分也都进行了修改。

建议你重新 clone 一下代码，因为在修改的过程中，我使用了强制提交，这可能会给你带来一些问题。
